### ISSUE TITLE
Cannot connect m5stickC or m5stickCplus to Tally Arbiter 1.5.1

### ISSUE THREAD

**Issue by lukie** [josephdadams/TallyArbiter-M5StickCListener#14]
Hi - I'm having no success getting either my m5sitckC or m5stickCplus units to register with Tally Arbiter.  They connect to the wifi almost instantly, but then just sit on "connecting to Tally Arbiter host: 192.168.65.6 - the serial output from them just says time -> [SIoC] Disconnected! every 500ms or so.  I've gone over all the obvious things like double-checking IP address, reflashing multiple times etc. etc.  without luck.  Any tips on what I might be doing wrong, or how to diagnose what is going wrong..?

**Comment by josephdadams** [comment]
Downgrade the TA server to socketio 2.3.0 by typing in the root server folder: `npm install socket.io@2.3.0`

**Comment by lukie** [comment]
That worked!  thankyou.  Although now I have a new problem - my M5sitck is connected.  It will see the change in camera, and I can make it flash.  But it is not seeing the program or preview changes for the cam it's connected to.  They're not appearing in the serial output either (whereas the flash and listener_reassign_object messages and flash messages are)

**Comment by josephdadams** [comment]
Can you try `1.5.3` and let me know if it helps with this issue?

**Comment by lukie** [comment]
That fixed it :-)  Thankyou so much Joseph, this work is so appreciated.  Cheers...

**Comment by mmattausch** [comment]
> Downgrade the TA server to socketio 2.3.0 by typing in the root server folder: `npm install socket.io@2.3.0`

Had the same issue - Downgrading to socketio 2.3.0 worked for me

**Comment by josephdadams** [comment]
I rolled back TA to default to 2.3.0 for now, and will have to sit down and figure out a roadmap to latest socketio at some point.
