### ISSUE TITLE
Bad DeviceID reported for M5stickc device

### ISSUE THREAD

**Issue by imorrish** [josephdadams/TallyArbiter-M5StickCListener#15]
I have 2 M5Stickc's. One works fine, the other connects but stays Unnasigned.
Serial monitor shows that the DeviceID looks invalid. "deviceId": ","c510bde4"
I can't figure out where this value comes from and why it has the extra ",

Bad unit 
Connected to Tally Arbiter server.
[SIoC] add packet 42["bus_options"]
[SIoC] add packet 42["device_listen_m5",{"deviceId": ","c510bde4", "listenerType": "m5-stickc"}]
[SIoC] packet "42["bus_options"]" emitted
[SIoC] packet "42["device_listen_m5",{"deviceId": ","c510bde4", "listenerType": "m5-stickc"}]" emitted
[SIoC] trigger event bus_option

Good unit
Connected to Tally Arbiter server.
[SIoC] add packet 42["bus_options"]
[SIoC] add packet 42["device_listen_m5",{"deviceId": "b1282c78", "listenerType": "m5-stickc"}]
[SIoC] packet "42["bus_options"]" emitted
[SIoC] packet "42["device_listen_m5",{"deviceId": "b1282c78", "listenerType": "m5-stickc"}]" emitted
[SIoC] trigger event bus_options

**Comment by imorrish** [comment]
Thanks, where would it store this old listener deviceID info? I can't see anything in the json file but the admin web page shows old listeners greyed out (although not this faulty one).
I was using WiFi Hotspot sharing on Windows 10 for the M5Stickc's, same machine running TallyArbiter, all listeners show the same IP address (default nic of the host) and not the private ip allocated by the hotspot.

**Comment by josephdadams** [comment]
On the m5stick, it's stored in internal memory. I'm using the Preferences.h library to do that. So my assumption is that when it goes through the Reassign process, it gets a faulty deviceID (which is parsed from the payload) and stores it. So I guess that's where it is happening. No one else has reported this, so I'm not quite sure how it's happening yet.

As far as clearing that out, I think you would have to flash a different program onto the device and then reflash this listener client to it.

**Comment by imorrish** [comment]
I tried reflashing it with the factory demo. Didn't change the deviceID. Might need a small app that actually clears out the flash memory, will try this http://iot-bits.com/erase-esp32-flash-completely/

**Comment by josephdadams** [comment]
This core issue of the device ID problem should be fixed in the latest commit.
