### ISSUE TITLE
M5StickC-Plus will not register in webpanel

### ISSUE THREAD

**Issue by Akibakki** [josephdadams/TallyArbiter-M5StickCListener#18]
Hi....
Had things working, but could not make the server start at boot, so I did a new install of the tally arbiter server on a Raspberry Pi. 

Now I can not get the M5 stick to register on the webpanel. The display on the M5 stick says connected. 
I have also updated the M5 stick, but still no luck. I'm no big programmer, so I can't say what is wrong, but I have tried my bedst for hours......
I also have a M5 Atom. This works as expected. 
Hope this can be resolved...

Thanks!

**Comment by josephdadams** [comment]
There was a breaking change depending on what version of the server you were using based on the version of the client. So if you upgraded the server, you were wise to upgrade the client. I have heard of some people having an issue with their m5sticks not fully taking the new code, so they have to upload some other program onto it to fully erase it and then try again. Can you do that?

**Comment by Akibakki** [comment]
Hi.
I have now tried this multiple times, and still no luck. 
Is there a log or something I can hav a look at? See what is going on.
And just a recommendation. Could you place  version / date  info on the main web page?

Thanks

**Comment by Akibakki** [comment]
Hi again
You were right! The m5sticks did not fully take the code. I had a unused m5stick, and this one worked right away, after uploading the new code.

I ended up using Esay Loader's erase function, to get the other sticks working. 
https://docs.m5stack.com/#/en/core/m5stickc_plus?id=easyloader

Thanks...
