### ISSUE TITLE
Program crash with version 1.4

### ISSUE THREAD

**Issue by houtacheng** [josephdadams/TallyArbiter-M5StickCListener#2]
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Loading the stored Tally Arbiter configuration file.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Sources loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     1 Sources configured.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Devices loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     3 Devices configured.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Device Sources loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Device Actions loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter TSL Clients loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Cloud Destinations loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter Cloud Keys loaded.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Initiating Setup for Source: ATEM. Type: Blackmagic ATEM
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Source: ATEM  Creating ATEM Connection.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Source Setup Complete.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Initializing Device States.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Device States Initialized.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Setting up the REST API.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     REST API Setup Complete.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Starting socket.IO Setup.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Socket.IO Setup Complete.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Starting OSC Setup.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Starting HTTP Server.
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     OSC Sending Port Ready. Broadcasting on Port: 5958
[Mon Oct 19 2020 21:33:56 GMT-0300 (GMT-03:00)]     Tally Arbiter running on port 4455
TypeError: Cannot set property 'id' of undefined
    at GetDeviceByDeviceId (/Users/sunda/Downloads/TallyArbiter-master/index.js:4141:13)
    at Socket.<anonymous> (/Users/sunda/Downloads/TallyArbiter-master/index.js:588:17)
    at Socket.emit (events.js:315:20)
    at /Users/sunda/Downloads/TallyArbiter-master/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by josephdadams** [comment]
Can you try 1.4.1 and see if that resolves your issue?

**Comment by houtacheng** [comment]
1.4.1 is great!!!

Tue Oct 20 2020 00:18:40 GMT-0300 (GMT-03:00)]     Listener Client Connected. Type: m5stick-c Device: 01_Cam01
