### ISSUE TITLE
[SIoC] Disconnected!

### ISSUE THREAD

**Issue by sledzik1984** [josephdadams/TallyArbiter-M5StickCListener#3]
Sketch uploaded to M5StickC in serial console shows only: 

Connecting to Tally Arbiter host: 192.168.15.68 
[SIoC] Disconnected!
[SIoC] Disconnected!
[SIoC] Disconnected!
[SIoC] Disconnected!
[SIoC] Disconnected!

**Comment by josephdadams** [comment]
This error could be caused by any number of things. Your network configuration, a firewall, perhaps your M5StickC is on a separate network or subnet from your Tally Arbiter host. Which version of Tally Arbiter are you running? Is the Tally Arbiter server console output giving you any errors?

**Comment by sledzik1984** [comment]
After deleting Arduino IDE, reinstalling all deps - working 👍
