### ISSUE TITLE
M5StickCPlus Listener?

### ISSUE THREAD

**Issue by DachsbauTV** [josephdadams/TallyArbiter-M5StickCListener#4]
Hey Jospeh,

Just wanted to ask if you had any success installing the Listener on a Plus model?

Again to have this request cleaned up from the other thread: this is the error log I've got when trying to compile it:
https://paste.sh/Ah-otpOU#2BNM7hwTyYBzi9n5gp7GtfVT

Happy to help if you have use for my little to none programming knowledge 🙈

**Comment by josephdadams** [comment]
It installed just fine on mine, but it didn’t look so great. But it worked.

I am partnering with @guido-visser to use his M5 client (currently only supports vmix) to seamlessly integrate with TA. So changes are coming. In the meantime though, his client already supports the Plus model, and you can use it with TA through Vmix tally emulation. The latest version of TA does this emulation. It won’t show as a connected listener client, but it will work!

**Comment by DachsbauTV** [comment]
Sorry to be bothering you again about this.
 
I've had it successfully compiled and uploaded to the M5Stick+  but it can't connect to the Server. In the serial monitor I can see the following problem:
`[SIoC] Connected to url: /socket.io/?transport=websocket
[SIoC] trigger event connect
[SIoC] add packet 42["bus_options"]
[SIoC] add packet 42["device_listen_m5stick",{"deviceId": "unassigned"}]
[SIoC] packet "42["bus_options"]" emitted
[SIoC] packet "42["device_listen_m5stick",{"deviceId": "unassigned"}]" emitted
[SIoC] trigger event bus_options
[SIoC] Disconnected!
`
Any ideas what could cause the problem with the bus_options?

**Comment by DachsbauTV** [comment]
Alright
I have it running now, but I've had to manually assign `deviceID` and `deviceName` .

Weirdly enough I can still change the device in the TA web interface and it will show the correct Tally info (however it will not change device name on the display.)

**Comment by josephdadams** [comment]
Try this latest version and let me know how it works on your plus.

**Comment by DachsbauTV** [comment]
Thanks Jospeh!

I've just tried to compile the new version and I am getting an error, but i think it's because I've updated my Mac to BigSur...
I will try to find another computer and give it another go.

Traceback (most recent call last):
  File "esptool.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_posix.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
Failed to execute script esptool
Multiple libraries were found for "Arduino_JSON.h"
 Used: /Users/Fred/Documents/Arduino/libraries/Arduino_JSON
 Not used: /Users/Fred/Documents/Arduino/libraries/Arduino_JSON-master
Multiple libraries were found for "WiFi.h"
 Used: /Users/Fred/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 255
/Applications/Arduino.app/Contents/Java/arduino-builder returned 255
Error compiling for board M5Stick-C.

**Comment by josephdadams** [comment]
Yes this is a Big Sur error

**Comment by DachsbauTV** [comment]
I knew i shouldn't have done it, but the promise of a new exciting world just always finds my naive spot haha

**Comment by DachsbauTV** [comment]
Alrighty I have good news:

Using the new RC of the ESP32 board from here makes Arduino work flawlessly on BigSur: https://github.com/espressif/arduino-esp32/releases/download/1.0.5-rc4/package_esp32_dev_index.json

Also your new Listener works great! Love the new test mode!

I've added some minor changes to the Sketch which you might enjoy. I'll add them as suggestions to the rep soon.

Also I've seen that you included this here recently: https://github.com/themusicnerd/TallyArbiter-M5AtomMatrixListener
It has a feature which i was thinking about for a long time for the M5Stick: M5 button press changes camera number. This is an amazing feature for teams like us that have different setups for every show and quick changes on the fly. Maybe you could easily copy this feature into this listener?

Thanks again Joseph for the great work with all your software. I am really enjoying working with it.

**Comment by josephdadams** [comment]
Great job!

Talk to me more about the camera number. The matrix client, when you press the button, just cycles through 16 numbers. The numbers don’t particularly represent anything in Tally Arbiter.

Is this what you want? Or would you rather be able to assign a number or address to the device in Tally Arbiter, and when you assign a listener client to that device, it shows that number you assigned?

And then we change the button press feature to cycle through device assignments, or other functions.

**Comment by DachsbauTV** [comment]
The second, but without the assigned numbers on the M5 but the device name (as it is already)

Ideally a press of e.g. the M5 button circles through all defined devices and the change is visible on screen because the device name changes with the press and is pulled from the TA server (as it does already)

**Comment by josephdadams** [comment]
I think we can do this.
