### ISSUE TITLE
Potential increase to battery life

### ISSUE THREAD

**Issue by DachsbauTV** [josephdadams/TallyArbiter-M5StickCListener#5]
Hi Joseph,

At the moment I'm using the https://github.com/oneguyoneblog/tally-light-esp32-for-blackmagic-atem-switcher for my Plus sticks.
As the battery life was less than an hour I was looking for a way to increase it and actually found a way to more than double the time it kept running.
Maybe you and Guido could use it too:

  M5.begin();
  setCpuFrequencyMhz(80);
  btStop();

I've had no extra delay on the tally or any other problem due to the lower CPU frequency. Booting the stick up takes about 2 seconds longer now.

Still looking how to turn off the Gyro to maybe extend battery life even more.

**Comment by DachsbauTV** [comment]
Also I've been trying this to lower the brightness with the decrease of the battery:
`  if (batteryLevel <= 15) {        // add brightness decrease when battery is low
    currentBrightness = 7;
    if (batteryLevel <= 30) {
      currentBrightness = 9;
      currentBrightness = 11;
    }`

**Comment by josephdadams** [comment]
What kind of increase in battery life have you seen with these improvements?

**Comment by DachsbauTV** [comment]
I have only measured it when I was still using the OneGuyOneBlog M5 tally but the result was phenomenal: it doubled the battery life

**Comment by DachsbauTV** [comment]
Oh and I've experienced that the batteries won't last as long with the TA compared to the much simpler OGOB ATEM Tally.

I guess it probably has to do with a more complex and constant communication between the listeners and the server. So to make the M5s last longer in a future major update, it should be looked into which requests can be reduced or just be pushed from the server.

**Comment by josephdadams** [comment]
You're correct, it does maintain an open socketio connection to the device. There are other ways to communicate, but this allows for event-based in either direction.

I'm interested in some optimization but also think that usb battery banks are fairly affordable and can be micro in size, so it isn't too much more to add an external battery like that and give it more life that way as well.

**Comment by DachsbauTV** [comment]
fair enough :)
I've bought some Atom TailBats too which are already enough to keep it running for about an hour.

**Comment by josephdadams** [comment]
I'm going to close this since some of the suggestions are now active in the code, and it's on the to-do-list to refactor the client at some point to just become a simple TCP listener rather than maintaining the constant connection. This ought to help with battery life. I can't say when I would get that done though, so if someone wanted to submit a PR for that, I would definitely look at it.
